#!/bin/sh
#
# Startup / shutdown script for the skydns daemon
#
# Copyright (c) 2011, FunPlus, Inc.
# All rights reserved
#
#
### BEGIN INIT INFO
# Provides:          skydns
# Required-Start:    $network $local_fs
# Required-Stop:
# Should-Start:      $named
# Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    skydns daemon 
# Description:          skydns daemon

### END INIT INFO

. /etc/init.d/functions

if [ "$(id -u)" != "0" ]; then
    echo "Must run as root"
    exit 1
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

SKYDNS_HOME=/var/wd/skydns/skydns
DAEMON=$SKYDNS_HOME/skydns

test -f $DAEMON || exit 0

# Otherwise, RHEL (and apparently Fedora) tries to "help" and set soft
# limit of core file size to 0 for daemons. It's done as part of
# daemon shell function shortly after changing user. See MB-6601
DAEMON_COREFILE_LIMIT=unlimited

start() {
    cd $SKYDNS_HOME
    ulimit -n 40960
    ulimit -c unlimited
    ulimit -l unlimited
    export ETCD_MACHINES='http://127.0.0.1:2379'
    /var/wd/skydns/skydns/etcd &
    $DAEMON -addr 0.0.0.0:53 -rcache-ttl 3600 -nameservers 114.114.114.114:53,8.8.8.8:53 -domain ffan.com -machines http://127.0.0.1:2379 &
    errcode=$?
    return $errcode
}

stop() {
    killall skydns
    killall etcd
    errcode=$?
    return $errcode
}

case $1 in
    start)
        echo -n $"Starting skydns-daemon"
        start
        echo
        ;;
    stop)
        echo -n $"Stopping skydns-daemon"
        stop
        echo
        ;;
    restart)
        echo -n $"Stopping skydns-daemon"
        stop
        echo
        echo -n $"Starting skydns-daemon"
        start
        echo
        ;;
    status)
        if running ; then
            echo "skydns-daemon is running"
            exit 0
        else
            echo "skydns-daemon is not running"
            exit 3
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/skydns {start|stop|restart|status}" >&2
        exit 3
esac
